version: '3'

services:
  description:
    build: kickstarter_description/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  database:
    image: mongo:latest
    ports: 
      - '27017:27017'